### ISSUE TITLE
[fix] Ajustar ordem de linhas na interface

### ISSUE THREAD

**Issue by fernandascovino** [RJ-SMTR/mobilidade-rio-app#31]
* Linhas do tipo `2XXX` são rodoviárias, devem vir após as linhas regulares

**Comment by fernandascovino** [comment]
@Gabriel0109 terminou todos os ajustes?

**Comment by Gabriel0109** [comment]
> @Gabriel0109 terminou todos os ajustes?

Terminei!

**Comment by fernandascovino** [comment]
ah blz, quando ce criar o PR coloca eu e @gmartinsoc como revisores pfvr

**Comment by fernandascovino** [comment]
a gente só fecha aqui quando o PR for meregeado, vou reabrir
