### ISSUE TITLE
Adicionar tela de pontos do BRT

### ISSUE THREAD

**Issue by fernandascovino** [RJ-SMTR/mobilidade-rio-app#51]
## Objetivo

Reproduzir tela de informação das linhas que passam nos pontos do SPPO com o tema do BRT (layout definido de acordo com o `route_type`)

**Comment by fernandascovino** [comment]
Comentários do @Gabriel0109 : Deixar variáveis do sass dinâmicas e parte dos cards (nome do ponto e qual lado o embarque na estação) condicionais por esse route_type também

**Comment by gmartinsoc** [comment]
Sugestões:
- Nas duas estações do mesmo conjunto, usar um único código.
- Na hora de mostrar para o cidadão, mostrar todos os serviços que passam nas duas estações "filhas".
- Na hora de selecionar o serviço desejado, apontar a direção e qual o plataforma que ele tem que se dirigir (expressa ou paradora), informação será preenchida em stop_desc.
