### ISSUE TITLE
Buscar infos do ponto/estação pelo nome

### ISSUE THREAD

**Issue by fernandascovino** [RJ-SMTR/mobilidade-rio-app#52]
## Objetivo

Hoje a busca é feita somente pelo código do ponto, idealmente queremos que seja possível buscar pelo nome da estação (principalmente para o BRT onde o nome da estação fica grande logo na entrada).

- A busca deve ser pelo nome que **contém** o termo buscado, e não match exato (ex: "24 de maio" deve identificar o ponto "BRS 1,2,3: 24 de maio")

**Comment by yxuo** [comment]
PR feito para main, a feature funciona até o momento.
