### ISSUE TITLE
Garagem que não apaga posições de veículos

### ISSUE THREAD

**Issue by fernandascovino** [RJ-SMTR/mobilidade-rio-app#66]
@Gabriel0109 adicionar descrição do problema + print da tela

**Comment by Gabriel0109** [comment]
![Image](https://user-images.githubusercontent.com/82231197/216447068-815f9c9e-1cdb-4f13-a733-44a566be27a8.png)

Nessa garagem específica os ônibus que estão dentro dela continuam aparecendo. Função que checa se está dentro ou não é a booleanPointInPolygon(https://turfjs.org/docs/#booleanPointInPolygon) do TurfJS. Nas outras garagens apaga normalmente.

**Comment by fernandascovino** [comment]
@Gabriel0109  eixa pfvr a referência da branch onde achar o código tbm
