### ISSUE TITLE
Adicionar destaque de veículos selecionados

### ISSUE THREAD

**Issue by fernandascovino** [RJ-SMTR/mobilidade-rio-app#67]
- Uma vez selecionado um ponto, mostrar todos os veiculos relacionados ao ponto (i.e. que estejam operando serviços que passam no ponto)
- Uma vez selecionado o sentido e/ou linha, deixar em destaque apenas os veículos filtrados e os demais apagados/acinzentados.

**Comment by yxuo** [comment]
### Selecionado um ponto, mostrar todos os veículos que passam por lá:
![Image](https://user-images.githubusercontent.com/54970870/226375547-8894cd56-885d-4657-95df-1d5d1d7a1531.png)
---
### Selecionado o sentido e/ou linha, destacar aquele veículo em relação aos demais:
![Image](https://user-images.githubusercontent.com/54970870/226374815-7748e5d5-778a-4ad9-895a-d959a507de90.png)
---
Será fechado pois as funcionalidades estão em staging
